import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const categories = [
  { titleFa: "قهوه گرم", titleEn: "Hot Coffee", slug: "cafe-hot-coffee", sortOrder: 1 },
  { titleFa: "قهوه سرد", titleEn: "Cold Coffee", slug: "cafe-cold-coffee", sortOrder: 2 },
  { titleFa: "چای و دمنوش", titleEn: "Tea & Herbal Drinks", slug: "cafe-tea-herbal", sortOrder: 3 },
  { titleFa: "نوشیدنی سرد", titleEn: "Cold Beverages", slug: "cafe-cold-beverages", sortOrder: 4 },
  { titleFa: "میلک‌شیک", titleEn: "Milkshakes", slug: "cafe-milkshakes", sortOrder: 5 },
  { titleFa: "کیک و دسر", titleEn: "Cakes & Desserts", slug: "cafe-cakes-desserts", sortOrder: 6 },
  { titleFa: "صبحانه و غذای سبک", titleEn: "Breakfast & Light Meals", slug: "cafe-breakfast-light-meals", sortOrder: 7 },
  { titleFa: "برگر", titleEn: "Burgers", slug: "fastfood-burgers", sortOrder: 8 },
  { titleFa: "پیتزا", titleEn: "Pizza", slug: "fastfood-pizza", sortOrder: 9 },
  { titleFa: "ساندویچ و هات‌داگ", titleEn: "Sandwiches & Hotdogs", slug: "fastfood-sandwiches-hotdogs", sortOrder: 10 },
  { titleFa: "مرغ سوخاری", titleEn: "Fried Chicken", slug: "fastfood-fried-chicken", sortOrder: 11 },
  { titleFa: "سیب‌زمینی و اسنک", titleEn: "Fries & Snacks", slug: "fastfood-fries-snacks", sortOrder: 12 },
  { titleFa: "سالاد", titleEn: "Salads", slug: "fastfood-salads", sortOrder: 13 },
  { titleFa: "سس و افزودنی", titleEn: "Sauces & Add-ons", slug: "fastfood-sauces-addons", sortOrder: 14 },
  { titleFa: "نوشابه", titleEn: "Soft Drinks", slug: "fastfood-soft-drinks", sortOrder: 15 },
];

const products = [
  {
    categorySlug: "cafe-hot-coffee",
    titleFa: "اسپرسو کلاسیک",
    titleEn: "Classic Espresso",
    shortDescFa: "شات اسپرسو با کرمای غلیظ",
    shortDescEn: "Single-shot espresso with rich crema",
    fullDescFa: "قهوه ۱۰۰٪ عربیکا با عطر قوی و طعم تلخ متعادل.",
    fullDescEn: "100% Arabica beans, bold aroma, balanced bitterness.",
    ingredientsFa: "قهوه عربیکا",
    ingredientsEn: "Arabica coffee",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 85000,
    images: ["https://images.unsplash.com/photo-1511920170033-f8396924c348"],
    tags: ["Strong"],
  },
  {
    categorySlug: "cafe-hot-coffee",
    titleFa: "لاته وانیل",
    titleEn: "Vanilla Latte",
    shortDescFa: "لاته با سیروپ وانیل",
    shortDescEn: "Latte with vanilla syrup",
    fullDescFa: "ترکیب اسپرسو، شیر بخار داده و وانیل.",
    fullDescEn: "Espresso, steamed milk, and vanilla syrup.",
    ingredientsFa: "اسپرسو، شیر، وانیل",
    ingredientsEn: "Espresso, milk, vanilla",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 140000,
    images: ["https://images.unsplash.com/photo-1517705008128-361805f42e86"],
    tags: ["Popular"],
  },
  {
    categorySlug: "cafe-cold-coffee",
    titleFa: "آیس لاته",
    titleEn: "Iced Latte",
    shortDescFa: "لاته خنک با یخ",
    shortDescEn: "Chilled latte over ice",
    fullDescFa: "اسپرسو دوبل با شیر خنک و یخ.",
    fullDescEn: "Double espresso with chilled milk and ice.",
    ingredientsFa: "اسپرسو، شیر، یخ",
    ingredientsEn: "Espresso, milk, ice",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 150000,
    images: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735"],
    tags: ["Cold"],
  },
  {
    categorySlug: "cafe-tea-herbal",
    titleFa: "چای سبز با نعنا",
    titleEn: "Mint Green Tea",
    shortDescFa: "چای سبز تازه و معطر",
    shortDescEn: "Freshly brewed green tea with mint",
    fullDescFa: "دمنوش سبک و آرام‌بخش با نعنا تازه.",
    fullDescEn: "Light and calming infusion with fresh mint.",
    ingredientsFa: "چای سبز، نعنا",
    ingredientsEn: "Green tea, mint",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 90000,
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93"],
    tags: ["Herbal"],
  },
  {
    categorySlug: "cafe-cold-beverages",
    titleFa: "موهیتو کلاسیک",
    titleEn: "Classic Mojito",
    shortDescFa: "نوشیدنی خنک نعنا و لیمو",
    shortDescEn: "Mint and lime cooler",
    fullDescFa: "لیموی تازه، نعنا و سودا.",
    fullDescEn: "Fresh lime, mint, and soda.",
    ingredientsFa: "لیمو، نعنا، سودا",
    ingredientsEn: "Lime, mint, soda",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 135000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Refreshing"],
  },
  {
    categorySlug: "cafe-milkshakes",
    titleFa: "میلک‌شیک شکلات",
    titleEn: "Chocolate Milkshake",
    shortDescFa: "میلک‌شیک غلیظ شکلاتی",
    shortDescEn: "Thick chocolate shake",
    fullDescFa: "بستنی و شیر تازه با شکلات تلخ.",
    fullDescEn: "Fresh milk, ice cream, and dark chocolate.",
    ingredientsFa: "شیر، بستنی، شکلات",
    ingredientsEn: "Milk, ice cream, chocolate",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 165000,
    images: ["https://images.unsplash.com/photo-1511910849309-0dffb3f9f347"],
    tags: ["Sweet"],
  },
  {
    categorySlug: "cafe-cakes-desserts",
    titleFa: "چیزکیک نیویورکی",
    titleEn: "New York Cheesecake",
    shortDescFa: "چیزکیک خامه‌ای کلاسیک",
    shortDescEn: "Classic creamy cheesecake",
    fullDescFa: "ترکیبی از پنیر خامه‌ای و بیسکویت.",
    fullDescEn: "Cream cheese blend with biscuit crust.",
    ingredientsFa: "پنیر خامه‌ای، بیسکویت",
    ingredientsEn: "Cream cheese, biscuit",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 190000,
    images: ["https://images.unsplash.com/photo-1505250469679-203ad9ced0cb"],
    tags: ["Dessert"],
  },
  {
    categorySlug: "cafe-breakfast-light-meals",
    titleFa: "املت مدیترانه‌ای",
    titleEn: "Mediterranean Omelette",
    shortDescFa: "املت با سبزیجات تازه",
    shortDescEn: "Omelette with fresh veggies",
    fullDescFa: "تخم‌مرغ، گوجه، فلفل دلمه و پنیر.",
    fullDescEn: "Eggs, tomatoes, bell pepper, and cheese.",
    ingredientsFa: "تخم‌مرغ، گوجه، پنیر",
    ingredientsEn: "Eggs, tomato, cheese",
    allergensFa: "تخم‌مرغ، لبنیات",
    allergensEn: "Eggs, dairy",
    price: 175000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Breakfast"],
  },
  {
    categorySlug: "fastfood-burgers",
    titleFa: "برگر کلاسیک",
    titleEn: "Classic Burger",
    shortDescFa: "گوشت تازه با پنیر و سس ویژه",
    shortDescEn: "Fresh beef, cheese, and house sauce",
    fullDescFa: "برگر ۱۵۰ گرمی با نان بریوش.",
    fullDescEn: "150g beef patty on brioche bun.",
    ingredientsFa: "گوشت، پنیر، نان",
    ingredientsEn: "Beef, cheese, bun",
    allergensFa: "گلوتن، لبنیات",
    allergensEn: "Gluten, dairy",
    price: 240000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Popular"],
  },
  {
    categorySlug: "fastfood-pizza",
    titleFa: "پیتزا مارگاریتا",
    titleEn: "Margherita Pizza",
    shortDescFa: "پنیر موزارلا و ریحان تازه",
    shortDescEn: "Mozzarella and fresh basil",
    fullDescFa: "خمیر نازک با سس گوجه و پنیر.",
    fullDescEn: "Thin crust with tomato sauce and cheese.",
    ingredientsFa: "پنیر، گوجه، ریحان",
    ingredientsEn: "Cheese, tomato, basil",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 310000,
    images: ["https://images.unsplash.com/photo-1542281286-9e0a16bb7366"],
    tags: ["Vegetarian"],
  },
  {
    categorySlug: "fastfood-sandwiches-hotdogs",
    titleFa: "هات‌داگ مخصوص",
    titleEn: "Signature Hotdog",
    shortDescFa: "هات‌داگ با سس مخصوص",
    shortDescEn: "Hotdog with house sauce",
    fullDescFa: "سوسیس گریل شده با نان تازه.",
    fullDescEn: "Grilled sausage with fresh bun.",
    ingredientsFa: "سوسیس، نان، سس",
    ingredientsEn: "Sausage, bun, sauce",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 175000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Classic"],
  },
  {
    categorySlug: "fastfood-fried-chicken",
    titleFa: "مرغ سوخاری ترد",
    titleEn: "Crispy Fried Chicken",
    shortDescFa: "مرغ سوخاری با ادویه مخصوص",
    shortDescEn: "Fried chicken with signature spices",
    fullDescFa: "پخت دوبل با بافت ترد و آبدار.",
    fullDescEn: "Double-fried for crispiness and juiciness.",
    ingredientsFa: "مرغ، آرد، ادویه",
    ingredientsEn: "Chicken, flour, spices",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 265000,
    images: ["https://images.unsplash.com/photo-1562967916-eb82221dfb32"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-fries-snacks",
    titleFa: "سیب‌زمینی چیلی",
    titleEn: "Chili Fries",
    shortDescFa: "سیب‌زمینی با سس چیلی",
    shortDescEn: "Fries with chili sauce",
    fullDescFa: "سیب‌زمینی سرخ‌شده با سس چیلی.",
    fullDescEn: "Crispy fries topped with chili sauce.",
    ingredientsFa: "سیب‌زمینی، سس چیلی",
    ingredientsEn: "Potato, chili sauce",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 120000,
    images: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-salads",
    titleFa: "سالاد سزار",
    titleEn: "Caesar Salad",
    shortDescFa: "سالاد با سس سزار",
    shortDescEn: "Salad with Caesar dressing",
    fullDescFa: "کاهو، مرغ گریل، پنیر پارمزان.",
    fullDescEn: "Romaine, grilled chicken, parmesan.",
    ingredientsFa: "کاهو، مرغ، پنیر",
    ingredientsEn: "Lettuce, chicken, cheese",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 195000,
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd"],
    tags: ["Healthy"],
  },
  {
    categorySlug: "fastfood-sauces-addons",
    titleFa: "سس سیر",
    titleEn: "Garlic Sauce",
    shortDescFa: "سس سیر خانگی",
    shortDescEn: "House-made garlic sauce",
    fullDescFa: "سس سیر خامه‌ای مناسب برگر و سیب‌زمینی.",
    fullDescEn: "Creamy garlic sauce for burgers and fries.",
    ingredientsFa: "سیر، مایونز",
    ingredientsEn: "Garlic, mayo",
    allergensFa: "تخم‌مرغ",
    allergensEn: "Eggs",
    price: 45000,
    images: ["https://images.unsplash.com/photo-1499636136210-6f4ee915583e"],
    tags: ["Addon"],
  },
  {
    categorySlug: "fastfood-soft-drinks",
    titleFa: "نوشابه کولا",
    titleEn: "Cola",
    shortDescFa: "نوشابه گازدار",
    shortDescEn: "Sparkling soft drink",
    fullDescFa: "نوشابه کلاسیک خنک.",
    fullDescEn: "Classic chilled cola.",
    ingredientsFa: "آب گازدار",
    ingredientsEn: "Carbonated water",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 55000,
    images: ["https://images.unsplash.com/photo-1541976076758-347942db1970"],
    tags: ["Cold"],
  },
];

async function main() {
  const adminPassword = process.env.ADMIN_PASSWORD || "ChangeMe123!";
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  await prisma.user.upsert({
    where: { email: "admin@foodo.local" },
    update: { passwordHash },
    create: {
      email: "admin@foodo.local",
      passwordHash,
      role: "ADMIN",
    },
  });

  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: {
        titleFa: category.titleFa,
        titleEn: category.titleEn,
        sortOrder: category.sortOrder,
      },
      create: category,
    });
  }

  const categoryMap = new Map(
    (await prisma.category.findMany()).map((c) => [c.slug, c.id])
  );

  for (const product of products) {
    const categoryId = categoryMap.get(product.categorySlug);
    if (!categoryId) continue;

    await prisma.product.upsert({
      where: {
        id: `${product.categorySlug}-${product.titleEn}`.toLowerCase().replace(/\s+/g, "-")
      },
      update: {
        categoryId,
        titleFa: product.titleFa,
        titleEn: product.titleEn,
        shortDescFa: product.shortDescFa,
        shortDescEn: product.shortDescEn,
        fullDescFa: product.fullDescFa,
        fullDescEn: product.fullDescEn,
        ingredientsFa: product.ingredientsFa,
        ingredientsEn: product.ingredientsEn,
        allergensFa: product.allergensFa,
        allergensEn: product.allergensEn,
        price: product.price,
        images: product.images,
        tags: product.tags,
        isAvailable: true,
      },
      create: {
        id: `${product.categorySlug}-${product.titleEn}`.toLowerCase().replace(/\s+/g, "-"),
        categoryId,
        titleFa: product.titleFa,
        titleEn: product.titleEn,
        shortDescFa: product.shortDescFa,
        shortDescEn: product.shortDescEn,
        fullDescFa: product.fullDescFa,
        fullDescEn: product.fullDescEn,
        ingredientsFa: product.ingredientsFa,
        ingredientsEn: product.ingredientsEn,
        allergensFa: product.allergensFa,
        allergensEn: product.allergensEn,
        price: product.price,
        images: product.images,
        tags: product.tags,
        isAvailable: true,
        sortOrder: 0,
      },
    });
  }

  await prisma.setting.upsert({
    where: { id: "singleton" },
    update: {
      restaurantName: "FOODO",
      currency: "TOMAN",
    },
    create: {
      id: "singleton",
      restaurantName: "FOODO",
      currency: "TOMAN",
      seoTitle: "FOODO | Premium Restaurant & Cafe",
      seoDescription: "FOODO digital menu with cafe and fast food items.",
    },
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
