import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const categories = [
  { titleFa: "قهوه گرم", titleEn: "Hot Coffee", slug: "cafe-hot-coffee", sortOrder: 1 },
  { titleFa: "قهوه سرد", titleEn: "Cold Coffee", slug: "cafe-cold-coffee", sortOrder: 2 },
  { titleFa: "چای و دمنوش", titleEn: "Tea & Herbal Drinks", slug: "cafe-tea-herbal", sortOrder: 3 },
  { titleFa: "نوشیدنی سرد", titleEn: "Cold Beverages", slug: "cafe-cold-beverages", sortOrder: 4 },
  { titleFa: "میلک‌شیک", titleEn: "Milkshakes", slug: "cafe-milkshakes", sortOrder: 5 },
  { titleFa: "کیک و دسر", titleEn: "Cakes & Desserts", slug: "cafe-cakes-desserts", sortOrder: 6 },
  { titleFa: "صبحانه و غذای سبک", titleEn: "Breakfast & Light Meals", slug: "cafe-breakfast-light-meals", sortOrder: 7 },
  { titleFa: "برگر", titleEn: "Burgers", slug: "fastfood-burgers", sortOrder: 8 },
  { titleFa: "پیتزا", titleEn: "Pizza", slug: "fastfood-pizza", sortOrder: 9 },
  { titleFa: "ساندویچ و هات‌داگ", titleEn: "Sandwiches & Hotdogs", slug: "fastfood-sandwiches-hotdogs", sortOrder: 10 },
  { titleFa: "مرغ سوخاری", titleEn: "Fried Chicken", slug: "fastfood-fried-chicken", sortOrder: 11 },
  { titleFa: "سیب‌زمینی و اسنک", titleEn: "Fries & Snacks", slug: "fastfood-fries-snacks", sortOrder: 12 },
  { titleFa: "سالاد", titleEn: "Salads", slug: "fastfood-salads", sortOrder: 13 },
  { titleFa: "سس و افزودنی", titleEn: "Sauces & Add-ons", slug: "fastfood-sauces-addons", sortOrder: 14 },
  { titleFa: "نوشابه", titleEn: "Soft Drinks", slug: "fastfood-soft-drinks", sortOrder: 15 },
];

const products = [
  {
    categorySlug: "cafe-hot-coffee",
    titleFa: "اسپرسو کلاسیک",
    titleEn: "Classic Espresso",
    shortDescFa: "شات اسپرسو با کرمای غلیظ",
    shortDescEn: "Single-shot espresso with rich crema",
    fullDescFa: "قهوه ۱۰۰٪ عربیکا با عطر قوی و طعم تلخ متعادل.",
    fullDescEn: "100% Arabica beans, bold aroma, balanced bitterness.",
    ingredientsFa: "قهوه عربیکا",
    ingredientsEn: "Arabica coffee",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 85000,
    images: ["https://images.unsplash.com/photo-1511920170033-f8396924c348"],
    tags: ["Strong"],
  },
  {
    categorySlug: "cafe-hot-coffee",
    titleFa: "لاته وانیل",
    titleEn: "Vanilla Latte",
    shortDescFa: "لاته با سیروپ وانیل",
    shortDescEn: "Latte with vanilla syrup",
    fullDescFa: "ترکیب اسپرسو، شیر بخار داده و وانیل.",
    fullDescEn: "Espresso, steamed milk, and vanilla syrup.",
    ingredientsFa: "اسپرسو، شیر، وانیل",
    ingredientsEn: "Espresso, milk, vanilla",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 140000,
    images: ["https://images.unsplash.com/photo-1517705008128-361805f42e86"],
    tags: ["Popular"],
  },
  {
    categorySlug: "cafe-hot-coffee",
    titleFa: "کاپوچینو",
    titleEn: "Cappuccino",
    shortDescFa: "کاپوچینو با فوم شیر",
    shortDescEn: "Cappuccino with silky foam",
    fullDescFa: "اسپرسو دوبل با فوم شیر و دارچین.",
    fullDescEn: "Double espresso with milk foam and cinnamon.",
    ingredientsFa: "اسپرسو، شیر، دارچین",
    ingredientsEn: "Espresso, milk, cinnamon",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 130000,
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93"],
    tags: ["Classic"],
  },
  {
    categorySlug: "cafe-cold-coffee",
    titleFa: "آیس لاته",
    titleEn: "Iced Latte",
    shortDescFa: "لاته خنک با یخ",
    shortDescEn: "Chilled latte over ice",
    fullDescFa: "اسپرسو دوبل با شیر خنک و یخ.",
    fullDescEn: "Double espresso with chilled milk and ice.",
    ingredientsFa: "اسپرسو، شیر، یخ",
    ingredientsEn: "Espresso, milk, ice",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 150000,
    images: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735"],
    tags: ["Cold"],
  },
  {
    categorySlug: "cafe-cold-coffee",
    titleFa: "کلد برو",
    titleEn: "Cold Brew",
    shortDescFa: "قهوه سرد دم با طعم ملایم",
    shortDescEn: "Slow-brewed cold coffee",
    fullDescFa: "دم‌آوری طولانی با طعم ملایم و شیرینی طبیعی.",
    fullDescEn: "Slow steeping for smooth taste and natural sweetness.",
    ingredientsFa: "قهوه، آب",
    ingredientsEn: "Coffee, water",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 145000,
    images: ["https://images.unsplash.com/photo-1447933601403-0c6688de566e"],
    tags: ["Smooth"],
  },
  {
    categorySlug: "cafe-cold-coffee",
    titleFa: "آیس آمریکانو",
    titleEn: "Iced Americano",
    shortDescFa: "اسپرسو با آب سرد و یخ",
    shortDescEn: "Espresso with chilled water",
    fullDescFa: "طعم قهوه خالص با حس خنک.",
    fullDescEn: "Pure espresso flavor, served chilled.",
    ingredientsFa: "اسپرسو، آب، یخ",
    ingredientsEn: "Espresso, water, ice",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 120000,
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93"],
    tags: ["Cold"],
  },
  {
    categorySlug: "cafe-tea-herbal",
    titleFa: "چای سبز با نعنا",
    titleEn: "Mint Green Tea",
    shortDescFa: "چای سبز تازه و معطر",
    shortDescEn: "Freshly brewed green tea with mint",
    fullDescFa: "دمنوش سبک و آرام‌بخش با نعنا تازه.",
    fullDescEn: "Light and calming infusion with fresh mint.",
    ingredientsFa: "چای سبز، نعنا",
    ingredientsEn: "Green tea, mint",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 90000,
    images: ["https://images.unsplash.com/photo-1509042239860-f550ce710b93"],
    tags: ["Herbal"],
  },
  {
    categorySlug: "cafe-tea-herbal",
    titleFa: "دمنوش بابونه",
    titleEn: "Chamomile Tea",
    shortDescFa: "دمنوش آرام‌بخش بابونه",
    shortDescEn: "Calming chamomile infusion",
    fullDescFa: "گزینه‌ای سبک برای آرامش و ریلکس.",
    fullDescEn: "Light, relaxing herbal tea.",
    ingredientsFa: "بابونه",
    ingredientsEn: "Chamomile",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 95000,
    images: ["https://images.unsplash.com/photo-1451748266016-1b5c2b915b49"],
    tags: ["Relax"],
  },
  {
    categorySlug: "cafe-tea-herbal",
    titleFa: "چای ترش",
    titleEn: "Hibiscus Tea",
    shortDescFa: "چای ترش خنک و خوش‌عطر",
    shortDescEn: "Tart hibiscus tea",
    fullDescFa: "طعم ترش طبیعی با رنگ جذاب.",
    fullDescEn: "Naturally tart with vibrant color.",
    ingredientsFa: "گل ختمی",
    ingredientsEn: "Hibiscus",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 98000,
    images: ["https://images.unsplash.com/photo-1451748266016-1b5c2b915b49"],
    tags: ["Herbal"],
  },
  {
    categorySlug: "cafe-cold-beverages",
    titleFa: "موهیتو کلاسیک",
    titleEn: "Classic Mojito",
    shortDescFa: "نوشیدنی خنک نعنا و لیمو",
    shortDescEn: "Mint and lime cooler",
    fullDescFa: "لیموی تازه، نعنا و سودا.",
    fullDescEn: "Fresh lime, mint, and soda.",
    ingredientsFa: "لیمو، نعنا، سودا",
    ingredientsEn: "Lime, mint, soda",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 135000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Refreshing"],
  },
  {
    categorySlug: "cafe-cold-beverages",
    titleFa: "لیموناد تازه",
    titleEn: "Fresh Lemonade",
    shortDescFa: "لیموناد خنک با لیموی تازه",
    shortDescEn: "Chilled lemonade",
    fullDescFa: "ترکیب لیمو تازه و شیرینی متعادل.",
    fullDescEn: "Fresh lemon with balanced sweetness.",
    ingredientsFa: "لیمو، آب، شکر",
    ingredientsEn: "Lemon, water, sugar",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 120000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Cold"],
  },
  {
    categorySlug: "cafe-cold-beverages",
    titleFa: "آیس تی",
    titleEn: "Iced Tea",
    shortDescFa: "چای سرد با طعم لیمو",
    shortDescEn: "Iced tea with lemon",
    fullDescFa: "چای سرد ملایم با لیمو.",
    fullDescEn: "Light iced tea with lemon.",
    ingredientsFa: "چای، لیمو",
    ingredientsEn: "Tea, lemon",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 110000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Cold"],
  },
  {
    categorySlug: "cafe-milkshakes",
    titleFa: "میلک‌شیک شکلات",
    titleEn: "Chocolate Milkshake",
    shortDescFa: "میلک‌شیک غلیظ شکلاتی",
    shortDescEn: "Thick chocolate shake",
    fullDescFa: "بستنی و شیر تازه با شکلات تلخ.",
    fullDescEn: "Fresh milk, ice cream, and dark chocolate.",
    ingredientsFa: "شیر، بستنی، شکلات",
    ingredientsEn: "Milk, ice cream, chocolate",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 165000,
    images: ["https://images.unsplash.com/photo-1511910849309-0dffb3f9f347"],
    tags: ["Sweet"],
  },
  {
    categorySlug: "cafe-milkshakes",
    titleFa: "میلک‌شیک وانیل",
    titleEn: "Vanilla Milkshake",
    shortDescFa: "میلک‌شیک وانیلی کلاسیک",
    shortDescEn: "Classic vanilla milkshake",
    fullDescFa: "بستنی وانیلی با شیر تازه.",
    fullDescEn: "Vanilla ice cream blended with milk.",
    ingredientsFa: "شیر، بستنی وانیلی",
    ingredientsEn: "Milk, vanilla ice cream",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 155000,
    images: ["https://images.unsplash.com/photo-1511910849309-0dffb3f9f347"],
    tags: ["Classic"],
  },
  {
    categorySlug: "cafe-milkshakes",
    titleFa: "میلک‌شیک توت‌فرنگی",
    titleEn: "Strawberry Milkshake",
    shortDescFa: "میلک‌شیک با توت تازه",
    shortDescEn: "Milkshake with fresh strawberries",
    fullDescFa: "بستنی و شیر با توت‌فرنگی تازه.",
    fullDescEn: "Strawberry ice cream and milk.",
    ingredientsFa: "شیر، بستنی، توت‌فرنگی",
    ingredientsEn: "Milk, ice cream, strawberry",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 160000,
    images: ["https://images.unsplash.com/photo-1497534446932-c925b458314e"],
    tags: ["Fruit"],
  },
  {
    categorySlug: "cafe-cakes-desserts",
    titleFa: "چیزکیک نیویورکی",
    titleEn: "New York Cheesecake",
    shortDescFa: "چیزکیک خامه‌ای کلاسیک",
    shortDescEn: "Classic creamy cheesecake",
    fullDescFa: "ترکیبی از پنیر خامه‌ای و بیسکویت.",
    fullDescEn: "Cream cheese blend with biscuit crust.",
    ingredientsFa: "پنیر خامه‌ای، بیسکویت",
    ingredientsEn: "Cream cheese, biscuit",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 190000,
    images: ["https://images.unsplash.com/photo-1505250469679-203ad9ced0cb"],
    tags: ["Dessert"],
  },
  {
    categorySlug: "cafe-cakes-desserts",
    titleFa: "براونی شکلاتی",
    titleEn: "Chocolate Brownie",
    shortDescFa: "براونی نرم با شکلات تلخ",
    shortDescEn: "Fudgy chocolate brownie",
    fullDescFa: "براونی گرم با بافت نرم و غلیظ.",
    fullDescEn: "Warm, fudgy brownie texture.",
    ingredientsFa: "شکلات، کره، آرد",
    ingredientsEn: "Chocolate, butter, flour",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 175000,
    images: ["https://images.unsplash.com/photo-1499636136210-6f4ee915583e"],
    tags: ["Chocolate"],
  },
  {
    categorySlug: "cafe-cakes-desserts",
    titleFa: "کیک هویج",
    titleEn: "Carrot Cake",
    shortDescFa: "کیک هویج با خامه پنیر",
    shortDescEn: "Carrot cake with cream cheese",
    fullDescFa: "کیک نرم با عطر دارچین.",
    fullDescEn: "Moist cake with cinnamon notes.",
    ingredientsFa: "هویج، آرد، پنیر خامه‌ای",
    ingredientsEn: "Carrot, flour, cream cheese",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 185000,
    images: ["https://images.unsplash.com/photo-1464349095431-e9a21285b5f3"],
    tags: ["Dessert"],
  },
  {
    categorySlug: "cafe-breakfast-light-meals",
    titleFa: "املت مدیترانه‌ای",
    titleEn: "Mediterranean Omelette",
    shortDescFa: "املت با سبزیجات تازه",
    shortDescEn: "Omelette with fresh veggies",
    fullDescFa: "تخم‌مرغ، گوجه، فلفل دلمه و پنیر.",
    fullDescEn: "Eggs, tomatoes, bell pepper, and cheese.",
    ingredientsFa: "تخم‌مرغ، گوجه، پنیر",
    ingredientsEn: "Eggs, tomato, cheese",
    allergensFa: "تخم‌مرغ، لبنیات",
    allergensEn: "Eggs, dairy",
    price: 175000,
    images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    tags: ["Breakfast"],
  },
  {
    categorySlug: "cafe-breakfast-light-meals",
    titleFa: "تست آووکادو",
    titleEn: "Avocado Toast",
    shortDescFa: "نان تست با آووکادو تازه",
    shortDescEn: "Toast topped with avocado",
    fullDescFa: "آووکادو، لیمو و ادویه‌های سبک.",
    fullDescEn: "Avocado, lemon, and light spices.",
    ingredientsFa: "نان، آووکادو، لیمو",
    ingredientsEn: "Bread, avocado, lemon",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 165000,
    images: ["https://images.unsplash.com/photo-1482049016688-2d3e1b311543"],
    tags: ["Light"],
  },
  {
    categorySlug: "cafe-breakfast-light-meals",
    titleFa: "فرنچ تست",
    titleEn: "French Toast",
    shortDescFa: "فرنچ تست با عسل",
    shortDescEn: "French toast with honey",
    fullDescFa: "نان تست برشته با عسل و دارچین.",
    fullDescEn: "Golden toast with honey and cinnamon.",
    ingredientsFa: "نان، تخم‌مرغ، عسل",
    ingredientsEn: "Bread, egg, honey",
    allergensFa: "گلوتن، تخم‌مرغ",
    allergensEn: "Gluten, eggs",
    price: 170000,
    images: ["https://images.unsplash.com/photo-1482049016688-2d3e1b311543"],
    tags: ["Breakfast"],
  },
  {
    categorySlug: "fastfood-burgers",
    titleFa: "برگر کلاسیک",
    titleEn: "Classic Burger",
    shortDescFa: "گوشت تازه با پنیر و سس ویژه",
    shortDescEn: "Fresh beef, cheese, and house sauce",
    fullDescFa: "برگر ۱۵۰ گرمی با نان بریوش.",
    fullDescEn: "150g beef patty on brioche bun.",
    ingredientsFa: "گوشت، پنیر، نان",
    ingredientsEn: "Beef, cheese, bun",
    allergensFa: "گلوتن، لبنیات",
    allergensEn: "Gluten, dairy",
    price: 240000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Popular"],
  },
  {
    categorySlug: "fastfood-burgers",
    titleFa: "برگر مرغ",
    titleEn: "Chicken Burger",
    shortDescFa: "فیله مرغ سوخاری با سس",
    shortDescEn: "Crispy chicken burger",
    fullDescFa: "فیله مرغ ترد با کاهو و سس ویژه.",
    fullDescEn: "Crispy chicken fillet with lettuce and sauce.",
    ingredientsFa: "مرغ، نان، کاهو",
    ingredientsEn: "Chicken, bun, lettuce",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 225000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Crispy"],
  },
  {
    categorySlug: "fastfood-burgers",
    titleFa: "برگر قارچ و پنیر",
    titleEn: "Mushroom Burger",
    shortDescFa: "برگر با قارچ و پنیر",
    shortDescEn: "Burger with mushrooms and cheese",
    fullDescFa: "ترکیب قارچ تازه با پنیر ذوب‌شده.",
    fullDescEn: "Fresh mushrooms with melted cheese.",
    ingredientsFa: "گوشت، قارچ، پنیر",
    ingredientsEn: "Beef, mushroom, cheese",
    allergensFa: "گلوتن، لبنیات",
    allergensEn: "Gluten, dairy",
    price: 255000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Signature"],
  },
  {
    categorySlug: "fastfood-pizza",
    titleFa: "پیتزا مارگاریتا",
    titleEn: "Margherita Pizza",
    shortDescFa: "پنیر موزارلا و ریحان تازه",
    shortDescEn: "Mozzarella and fresh basil",
    fullDescFa: "خمیر نازک با سس گوجه و پنیر.",
    fullDescEn: "Thin crust with tomato sauce and cheese.",
    ingredientsFa: "پنیر، گوجه، ریحان",
    ingredientsEn: "Cheese, tomato, basil",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 310000,
    images: ["https://images.unsplash.com/photo-1542281286-9e0a16bb7366"],
    tags: ["Vegetarian"],
  },
  {
    categorySlug: "fastfood-pizza",
    titleFa: "پیتزا پپرونی",
    titleEn: "Pepperoni Pizza",
    shortDescFa: "پپرونی و پنیر موزارلا",
    shortDescEn: "Pepperoni with mozzarella",
    fullDescFa: "طعم کلاسیک پپرونی با پنیر کشدار.",
    fullDescEn: "Classic pepperoni with stretchy cheese.",
    ingredientsFa: "پپرونی، پنیر، خمیر",
    ingredientsEn: "Pepperoni, cheese, dough",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 335000,
    images: ["https://images.unsplash.com/photo-1542281286-9e0a16bb7366"],
    tags: ["Popular"],
  },
  {
    categorySlug: "fastfood-pizza",
    titleFa: "پیتزا سبزیجات",
    titleEn: "Veggie Pizza",
    shortDescFa: "سبزیجات تازه و سس گوجه",
    shortDescEn: "Fresh veggies and tomato sauce",
    fullDescFa: "میکس سبزیجات با پنیر موزارلا.",
    fullDescEn: "Mixed vegetables with mozzarella.",
    ingredientsFa: "سبزیجات، پنیر، خمیر",
    ingredientsEn: "Vegetables, cheese, dough",
    allergensFa: "لبنیات، گلوتن",
    allergensEn: "Dairy, gluten",
    price: 320000,
    images: ["https://images.unsplash.com/photo-1542281286-9e0a16bb7366"],
    tags: ["Vegetarian"],
  },
  {
    categorySlug: "fastfood-sandwiches-hotdogs",
    titleFa: "هات‌داگ مخصوص",
    titleEn: "Signature Hotdog",
    shortDescFa: "هات‌داگ با سس مخصوص",
    shortDescEn: "Hotdog with house sauce",
    fullDescFa: "سوسیس گریل شده با نان تازه.",
    fullDescEn: "Grilled sausage with fresh bun.",
    ingredientsFa: "سوسیس، نان، سس",
    ingredientsEn: "Sausage, bun, sauce",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 175000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Classic"],
  },
  {
    categorySlug: "fastfood-sandwiches-hotdogs",
    titleFa: "کلاب ساندویچ",
    titleEn: "Club Sandwich",
    shortDescFa: "ساندویچ چند لایه با مرغ",
    shortDescEn: "Layered sandwich with chicken",
    fullDescFa: "مرغ گریل شده، سبزیجات و سس مخصوص.",
    fullDescEn: "Grilled chicken, veggies, and house sauce.",
    ingredientsFa: "مرغ، نان تست، سبزیجات",
    ingredientsEn: "Chicken, toast, veggies",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 195000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Popular"],
  },
  {
    categorySlug: "fastfood-sandwiches-hotdogs",
    titleFa: "هات‌داگ باربیکیو",
    titleEn: "BBQ Hotdog",
    shortDescFa: "هات‌داگ با سس باربیکیو",
    shortDescEn: "Hotdog with BBQ sauce",
    fullDescFa: "سوسیس گریل با سس باربیکیو دودی.",
    fullDescEn: "Grilled sausage with smoky BBQ sauce.",
    ingredientsFa: "سوسیس، نان، سس باربیکیو",
    ingredientsEn: "Sausage, bun, BBQ sauce",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 185000,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349"],
    tags: ["Smoky"],
  },
  {
    categorySlug: "fastfood-fried-chicken",
    titleFa: "مرغ سوخاری ترد",
    titleEn: "Crispy Fried Chicken",
    shortDescFa: "مرغ سوخاری با ادویه مخصوص",
    shortDescEn: "Fried chicken with signature spices",
    fullDescFa: "پخت دوبل با بافت ترد و آبدار.",
    fullDescEn: "Double-fried for crispiness and juiciness.",
    ingredientsFa: "مرغ، آرد، ادویه",
    ingredientsEn: "Chicken, flour, spices",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 265000,
    images: ["https://images.unsplash.com/photo-1562967916-eb82221dfb32"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-fried-chicken",
    titleFa: "بال مرغ تند",
    titleEn: "Spicy Wings",
    shortDescFa: "بال سوخاری با سس تند",
    shortDescEn: "Crispy wings with hot sauce",
    fullDescFa: "بال‌های ترد با سس تند ویژه.",
    fullDescEn: "Crispy wings tossed in hot sauce.",
    ingredientsFa: "مرغ، ادویه، سس تند",
    ingredientsEn: "Chicken, spices, hot sauce",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 230000,
    images: ["https://images.unsplash.com/photo-1562967916-eb82221dfb32"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-fried-chicken",
    titleFa: "استریپس مرغ",
    titleEn: "Chicken Tenders",
    shortDescFa: "تکه‌های ترد مرغ",
    shortDescEn: "Crispy chicken tenders",
    fullDescFa: "تکه‌های مرغ با پوشش ترد.",
    fullDescEn: "Tender chicken strips with crunchy coating.",
    ingredientsFa: "مرغ، آرد",
    ingredientsEn: "Chicken, flour",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 220000,
    images: ["https://images.unsplash.com/photo-1562967916-eb82221dfb32"],
    tags: ["Crispy"],
  },
  {
    categorySlug: "fastfood-fries-snacks",
    titleFa: "سیب‌زمینی چیلی",
    titleEn: "Chili Fries",
    shortDescFa: "سیب‌زمینی با سس چیلی",
    shortDescEn: "Fries with chili sauce",
    fullDescFa: "سیب‌زمینی سرخ‌شده با سس چیلی.",
    fullDescEn: "Crispy fries topped with chili sauce.",
    ingredientsFa: "سیب‌زمینی، سس چیلی",
    ingredientsEn: "Potato, chili sauce",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 120000,
    images: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-fries-snacks",
    titleFa: "سیب‌زمینی ترافل",
    titleEn: "Truffle Fries",
    shortDescFa: "سیب‌زمینی با سس ترافل",
    shortDescEn: "Fries with truffle sauce",
    fullDescFa: "طعم خاص ترافل با پنیر پارمزان.",
    fullDescEn: "Truffle aroma with parmesan finish.",
    ingredientsFa: "سیب‌زمینی، ترافل، پنیر",
    ingredientsEn: "Potato, truffle, cheese",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 150000,
    images: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb"],
    tags: ["Signature"],
  },
  {
    categorySlug: "fastfood-fries-snacks",
    titleFa: "حلقه پیاز",
    titleEn: "Onion Rings",
    shortDescFa: "حلقه‌های پیاز سوخاری",
    shortDescEn: "Crispy onion rings",
    fullDescFa: "حلقه‌های پیاز طلایی و ترد.",
    fullDescEn: "Golden fried onion rings.",
    ingredientsFa: "پیاز، آرد",
    ingredientsEn: "Onion, flour",
    allergensFa: "گلوتن",
    allergensEn: "Gluten",
    price: 110000,
    images: ["https://images.unsplash.com/photo-1541592106381-b31e9677c0e5"],
    tags: ["Snack"],
  },
  {
    categorySlug: "fastfood-salads",
    titleFa: "سالاد سزار",
    titleEn: "Caesar Salad",
    shortDescFa: "سالاد با سس سزار",
    shortDescEn: "Salad with Caesar dressing",
    fullDescFa: "کاهو، مرغ گریل، پنیر پارمزان.",
    fullDescEn: "Romaine, grilled chicken, parmesan.",
    ingredientsFa: "کاهو، مرغ، پنیر",
    ingredientsEn: "Lettuce, chicken, cheese",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 195000,
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd"],
    tags: ["Healthy"],
  },
  {
    categorySlug: "fastfood-salads",
    titleFa: "سالاد یونانی",
    titleEn: "Greek Salad",
    shortDescFa: "سالاد با زیتون و پنیر فتا",
    shortDescEn: "Salad with olives and feta",
    fullDescFa: "گوجه، خیار، زیتون و فتا.",
    fullDescEn: "Tomato, cucumber, olives, and feta.",
    ingredientsFa: "گوجه، خیار، پنیر فتا",
    ingredientsEn: "Tomato, cucumber, feta",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 180000,
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd"],
    tags: ["Fresh"],
  },
  {
    categorySlug: "fastfood-salads",
    titleFa: "سالاد کینوا",
    titleEn: "Quinoa Salad",
    shortDescFa: "سالاد سبک با کینوا",
    shortDescEn: "Light salad with quinoa",
    fullDescFa: "کینوا، سبزیجات تازه و لیمو.",
    fullDescEn: "Quinoa with fresh veggies and lemon.",
    ingredientsFa: "کینوا، سبزیجات",
    ingredientsEn: "Quinoa, vegetables",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 185000,
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd"],
    tags: ["Healthy"],
  },
  {
    categorySlug: "fastfood-sauces-addons",
    titleFa: "سس سیر",
    titleEn: "Garlic Sauce",
    shortDescFa: "سس سیر خانگی",
    shortDescEn: "House-made garlic sauce",
    fullDescFa: "سس سیر خامه‌ای مناسب برگر و سیب‌زمینی.",
    fullDescEn: "Creamy garlic sauce for burgers and fries.",
    ingredientsFa: "سیر، مایونز",
    ingredientsEn: "Garlic, mayo",
    allergensFa: "تخم‌مرغ",
    allergensEn: "Eggs",
    price: 45000,
    images: ["https://images.unsplash.com/photo-1499636136210-6f4ee915583e"],
    tags: ["Addon"],
  },
  {
    categorySlug: "fastfood-sauces-addons",
    titleFa: "سس مایونز تند",
    titleEn: "Spicy Mayo",
    shortDescFa: "مایونز با ادویه تند",
    shortDescEn: "Mayo with spicy kick",
    fullDescFa: "سس مایونز تند برای فست‌فود.",
    fullDescEn: "Spicy mayo for fast food.",
    ingredientsFa: "مایونز، ادویه",
    ingredientsEn: "Mayo, spices",
    allergensFa: "تخم‌مرغ",
    allergensEn: "Eggs",
    price: 45000,
    images: ["https://images.unsplash.com/photo-1499636136210-6f4ee915583e"],
    tags: ["Spicy"],
  },
  {
    categorySlug: "fastfood-sauces-addons",
    titleFa: "دیپ پنیر",
    titleEn: "Cheese Dip",
    shortDescFa: "دیپ پنیر گرم",
    shortDescEn: "Warm cheese dip",
    fullDescFa: "دیپ پنیر مناسب سیب‌زمینی.",
    fullDescEn: "Cheese dip for fries.",
    ingredientsFa: "پنیر، شیر",
    ingredientsEn: "Cheese, milk",
    allergensFa: "لبنیات",
    allergensEn: "Dairy",
    price: 60000,
    images: ["https://images.unsplash.com/photo-1499636136210-6f4ee915583e"],
    tags: ["Addon"],
  },
  {
    categorySlug: "fastfood-soft-drinks",
    titleFa: "نوشابه کولا",
    titleEn: "Cola",
    shortDescFa: "نوشابه گازدار",
    shortDescEn: "Sparkling soft drink",
    fullDescFa: "نوشابه کلاسیک خنک.",
    fullDescEn: "Classic chilled cola.",
    ingredientsFa: "آب گازدار",
    ingredientsEn: "Carbonated water",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 55000,
    images: ["https://images.unsplash.com/photo-1541976076758-347942db1970"],
    tags: ["Cold"],
  },
  {
    categorySlug: "fastfood-soft-drinks",
    titleFa: "لیموناد گازدار",
    titleEn: "Lemon Soda",
    shortDescFa: "نوشابه لیمویی",
    shortDescEn: "Lemon flavored soda",
    fullDescFa: "نوشابه خنک با طعم لیمو.",
    fullDescEn: "Refreshing lemon soda.",
    ingredientsFa: "آب گازدار، لیمو",
    ingredientsEn: "Carbonated water, lemon",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 60000,
    images: ["https://images.unsplash.com/photo-1541976076758-347942db1970"],
    tags: ["Cold"],
  },
  {
    categorySlug: "fastfood-soft-drinks",
    titleFa: "آب گازدار",
    titleEn: "Sparkling Water",
    shortDescFa: "آب گازدار ساده",
    shortDescEn: "Classic sparkling water",
    fullDescFa: "نوشیدنی ساده و بدون قند.",
    fullDescEn: "Simple, sugar-free sparkle.",
    ingredientsFa: "آب گازدار",
    ingredientsEn: "Carbonated water",
    allergensFa: "ندارد",
    allergensEn: "None",
    price: 50000,
    images: ["https://images.unsplash.com/photo-1541976076758-347942db1970"],
    tags: ["Light"],
  },
];

async function main() {
  const adminPassword = process.env.ADMIN_PASSWORD || "ChangeMe123!";
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  await prisma.user.upsert({
    where: { email: "admin@foodo.local" },
    update: { passwordHash },
    create: {
      email: "admin@foodo.local",
      passwordHash,
      role: "ADMIN",
    },
  });

  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: {
        titleFa: category.titleFa,
        titleEn: category.titleEn,
        sortOrder: category.sortOrder,
      },
      create: category,
    });
  }

  const categoryMap = new Map(
    (await prisma.category.findMany()).map((c) => [c.slug, c.id])
  );

  for (const product of products) {
    const categoryId = categoryMap.get(product.categorySlug);
    if (!categoryId) continue;

    await prisma.product.upsert({
      where: {
        id: `${product.categorySlug}-${product.titleEn}`.toLowerCase().replace(/\s+/g, "-")
      },
      update: {
        categoryId,
        titleFa: product.titleFa,
        titleEn: product.titleEn,
        shortDescFa: product.shortDescFa,
        shortDescEn: product.shortDescEn,
        fullDescFa: product.fullDescFa,
        fullDescEn: product.fullDescEn,
        ingredientsFa: product.ingredientsFa,
        ingredientsEn: product.ingredientsEn,
        allergensFa: product.allergensFa,
        allergensEn: product.allergensEn,
        price: product.price,
        images: product.images,
        tags: product.tags,
        isAvailable: true,
      },
      create: {
        id: `${product.categorySlug}-${product.titleEn}`.toLowerCase().replace(/\s+/g, "-"),
        categoryId,
        titleFa: product.titleFa,
        titleEn: product.titleEn,
        shortDescFa: product.shortDescFa,
        shortDescEn: product.shortDescEn,
        fullDescFa: product.fullDescFa,
        fullDescEn: product.fullDescEn,
        ingredientsFa: product.ingredientsFa,
        ingredientsEn: product.ingredientsEn,
        allergensFa: product.allergensFa,
        allergensEn: product.allergensEn,
        price: product.price,
        images: product.images,
        tags: product.tags,
        isAvailable: true,
        sortOrder: 0,
      },
    });
  }

  await prisma.setting.upsert({
    where: { id: "singleton" },
    update: {
      restaurantName: "FOODO",
      currency: "TOMAN",
      primaryColor: "#ff7a00",
      secondaryColor: "#ff9f1c",
    },
    create: {
      id: "singleton",
      restaurantName: "FOODO",
      currency: "TOMAN",
      primaryColor: "#ff7a00",
      secondaryColor: "#ff9f1c",
      seoTitle: "FOODO | Premium Restaurant & Cafe",
      seoDescription: "FOODO digital menu with cafe and fast food items.",
    },
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
